# Generated by Django 5.2.13 on 2026-06-10 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Check-In Email Address')),
                ('checkin_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Check-In Password')),
                ('checkin_password_enabled', models.BooleanField(default=True, verbose_name='Check-In Password Enabled')),
                ('private_email_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Private Email Username')),
                ('private_email_address_saved', models.BooleanField(default=False, verbose_name='Private Email Address Saved')),
                ('private_email_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Private Email Password')),
                ('private_email_password_saved', models.BooleanField(default=False, verbose_name='Private Email Password Saved')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_email_config', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Check-In Email Config',
                'verbose_name_plural': 'Check-In Email Configs',
            },
        ),
    ]
