# Generated by Django 5.2.13 on 2026-06-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_activeservice_billingrecord_checkinhistoryrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email of the submitter', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=255)),
                ('is_customer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Is the submitter currently a customer?', max_length=10)),
                ('message', models.TextField(help_text='The contact message body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ('-created_at',),
            },
        ),
    ]
