# Generated by Django 5.2.13 on 2026-06-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the submitter', max_length=150),
        ),
    ]
