# Generated by Django 5.2.13 on 2026-06-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_contactmessage_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservaultfile',
            name='encrypted_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uservaultfile',
            name='encryption_iv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uservaultfile',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uservaultfile',
            name='storage_bucket',
            field=models.IntegerField(default=1),
        ),
    ]
