# Generated by Django 5.2.13 on 2026-06-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_uservaultfile_encrypted_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gb', models.IntegerField(unique=True)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('gb',),
            },
        ),
    ]
