# Generated by Django 5.2.13 on 2026-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_storageplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressReleaseTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_index', models.IntegerField(help_text='0-indexed identifier, e.g. 0, 1, 2', unique=True)),
                ('count', models.CharField(help_text='e.g. 250, 500, 1,000+', max_length=50)),
                ('label', models.CharField(default='Media Outlets', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for upgrade. Leave empty/0 for standard.', max_digits=10, null=True)),
            ],
            options={
                'ordering': ('tier_index',),
            },
        ),
        migrations.AddField(
            model_name='pressreleaseconfig',
            name='category',
            field=models.CharField(default='Government corruption', max_length=255),
        ),
    ]
