# Generated by Django 5.2.13 on 2026-06-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_pressreleasetier_pressreleaseconfig_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressreleaseconfig',
            name='subject',
            field=models.CharField(default='URGENT: Critical Information Released', max_length=255),
        ),
    ]
