# Generated by Django 5.2.15 on 2026-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_checkin_magic_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinhistoryrecord',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='checkinhistoryrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
