# Generated by Django 5.2.15 on 2026-06-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_checkinhistoryrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservaultfile',
            name='error_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uservaultfile',
            name='staging_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uservaultfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
