# Generated by Django 5.2.15 on 2026-07-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_twofactorcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
