# Generated by Django 5.2.13 on 2026-06-12 20:08

from django.db import migrations, models


def populate_default_pricing(apps, schema_editor):
    CheckInOption = apps.get_model('payments', 'CheckInOption')
    AddOnOption = apps.get_model('payments', 'AddOnOption')

    # Default Check-In options
    check_in_defaults = [
        {"key": "daily", "label": "Daily Check-In", "display_label": "Daily", "price_per_month": 49.99, "price_1_year": 995.00, "price_2_years": 1799.00, "price_3_years": 2399.00},
        {"key": "weekly", "label": "Weekly Check-In", "display_label": "Weekly", "price_per_month": 29.99, "price_1_year": 595.00, "price_2_years": 995.00, "price_3_years": 1299.00},
        {"key": "monthly", "label": "Monthly Check-In", "display_label": "Monthly", "price_per_month": 14.99, "price_1_year": 329.00, "price_2_years": 595.00, "price_3_years": 759.00},
        {"key": "quarterly", "label": "Quarterly Check-In", "display_label": "Quarterly", "price_per_month": 9.99, "price_1_year": 259.00, "price_2_years": 399.00, "price_3_years": 595.00},
        {"key": "yearly", "label": "Yearly Check-In", "display_label": "Yearly", "price_per_month": 4.99, "price_1_year": 99.00, "price_2_years": 149.00, "price_3_years": 179.00},
    ]

    for item in check_in_defaults:
        CheckInOption.objects.get_or_create(key=item["key"], defaults=item)

    # Default Add-on options
    addon_defaults = [
        {"key": "private_email", "label": "Private Check-In Email Address", "description": "Surveillance-free email assigned exclusively to your account", "price": 39.00},
        {"key": "2fa", "label": "Two-Factor Authentication (2FA)", "description": "Time-sensitive codes providing a critical second barrier on every login", "price": 39.00},
        {"key": "extra_storage", "label": "Additional Storage (1GB)", "description": "Expand your vault for larger files and extensive archives", "price": 15.00},
        {"key": "press_release", "label": "Press Release", "description": "Automatically distribute your message to verified media outlets", "price": 59.00},
        {"key": "press_release_250", "label": "Press Release (250 outlets)", "description": "Press release tier 250", "price": 250.00},
        {"key": "press_release_500", "label": "Press Release (500 outlets)", "description": "Press release tier 500", "price": 495.00},
        {"key": "press_release_1000", "label": "Press Release (1000 outlets)", "description": "Press release tier 1000", "price": 695.00},
    ]

    for item in addon_defaults:
        AddOnOption.objects.get_or_create(key=item["key"], defaults=item)


def rollback_default_pricing(apps, schema_editor):
    CheckInOption = apps.get_model('payments', 'CheckInOption')
    AddOnOption = apps.get_model('payments', 'AddOnOption')
    CheckInOption.objects.all().delete()
    AddOnOption.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_gateway_fields_and_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g. private_email, 2fa, extra_storage, press_release, press_release_250, etc.', max_length=50, unique=True)),
                ('label', models.CharField(help_text='e.g. Private Check-In Email Address', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description for the add-on')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this add-on option', max_digits=10)),
            ],
            options={
                'verbose_name': 'Add-On Option',
                'verbose_name_plural': 'Add-On Options',
            },
        ),
        migrations.CreateModel(
            name='CheckInOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g. daily, weekly, monthly, quarterly, yearly', max_length=50, unique=True)),
                ('label', models.CharField(help_text='e.g. Daily Check-In', max_length=100)),
                ('display_label', models.CharField(help_text='e.g. Daily', max_length=50)),
                ('price_per_month', models.DecimalField(decimal_places=2, help_text='Used in pricing calculator page', max_digits=10)),
                ('price_1_year', models.DecimalField(decimal_places=2, help_text='Used in registration flow step 4 (1 Year)', max_digits=10)),
                ('price_2_years', models.DecimalField(decimal_places=2, help_text='Used in registration flow step 4 (2 Years)', max_digits=10)),
                ('price_3_years', models.DecimalField(decimal_places=2, help_text='Used in registration flow step 4 (3 Years)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Check-In Option',
                'verbose_name_plural': 'Check-In Options',
            },
        ),
        migrations.RunPython(populate_default_pricing, rollback_default_pricing),
    ]

