# Generated by Django 5.2.15 on 2026-06-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_addonoption_checkinoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_2_years_pct', models.IntegerField(default=5, help_text='Discount percentage for 2-year terms (e.g. 5 for 5%)')),
                ('discount_3_years_pct', models.IntegerField(default=10, help_text='Discount percentage for 3-year terms (e.g. 10 for 10%)')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
